services:
  # Laravel Backend Application
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: marknest-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./apps/backend:/var/www/html
      # - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Laravel storage bindings
      - ./docker/storage/app:/var/www/html/storage/app
      - ./docker/storage/framework:/var/www/html/storage/framework
      - ./docker/storage/logs:/var/www/html/storage/logs
      - ./docker/bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - ./.env
    environment:
      - APP_ENV=local
      - LOG_CHANNEL=daily
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
    depends_on:
      - db
      - redis
      # - rabbitmq
    networks:
      - marknest-network

  # PostgreSQL Database
  db:
    image: postgres:17.6
    container_name: marknest-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - marknest-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: marknest-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marknest-network

  # RabbitMQ Message Queue
  # rabbitmq:
  #   image: rabbitmq:4.1-management
  #   container_name: marknest-rabbitmq
  #   restart: unless-stopped
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=marknest
  #     - RABBITMQ_DEFAULT_PASS=password
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"  # Management UI
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   networks:
  #     - marknest-network

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: marknest-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - marknest-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  # rabbitmq_data:
  #   driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  marknest-network:
    driver: bridge